In [2]:
import numpy as np

In [3]:
a = np.zeros(10)

In [4]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
a.itemsize

8

In [8]:
b = len(a)*a.itemsize

In [9]:
b

80

In [11]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [13]:
a = np.arange(10,50)

In [14]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
b = a[-1:0:-1]

In [21]:
b

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11])

In [23]:
np.reshape(np.arange(0,9),(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

In [25]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = np.arange(5)

In [29]:
np.tile(a, (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [32]:
np.linspace(0,1,12)[1:11]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [48]:
a = np.random.rand(10)

In [49]:
a

array([0.89626222, 0.935968  , 0.40367513, 0.99140109, 0.46329282,
       0.04374128, 0.9356329 , 0.27350516, 0.20484475, 0.94866861])

In [40]:
help(np.argsort)

Help on _ArrayFunctionDispatcher in module numpy:

argsort(a, axis=-1, kind=None, order=None)
    Returns the indices that would sort an array.
    
    Perform an indirect sort along the given axis using the algorithm specified
    by the `kind` keyword. It returns an array of indices of the same shape as
    `a` that index data along the given axis in sorted order.
    
    Parameters
    ----------
    a : array_like
        Array to sort.
    axis : int or None, optional
        Axis along which to sort.  The default is -1 (the last axis). If None,
        the flattened array is used.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort under the covers and, in general, the
        actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           T

In [51]:
a[a[:].argsort()]


array([0.04374128, 0.20484475, 0.27350516, 0.40367513, 0.46329282,
       0.89626222, 0.9356329 , 0.935968  , 0.94866861, 0.99140109])

In [52]:
help(np.iinfo)

Help on class iinfo in module numpy:

class iinfo(builtins.object)
 |  iinfo(int_type)
 |  
 |  iinfo(type)
 |  
 |  Machine limits for integer types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  dtype : dtype
 |      Returns the dtype for which `iinfo` returns information.
 |  min : int
 |      The smallest integer expressible by the type.
 |  max : int
 |      The largest integer expressible by the type.
 |  
 |  Parameters
 |  ----------
 |  int_type : integer type, dtype, or instance
 |      The kind of integer data type to get information about.
 |  
 |  See Also
 |  --------
 |  finfo : The equivalent for floating point data types.
 |  
 |  Examples
 |  --------
 |  With types:
 |  
 |  >>> ii16 = np.iinfo(np.int16)
 |  >>> ii16.min
 |  -32768
 |  >>> ii16.max
 |  32767
 |  >>> ii32 = np.iinfo(np.int32)
 |  >>> ii32.min
 |  -2147483648
 |  >>> ii32.max
 |  2147483647
 |  
 |  With instances:
 |  
 |  >>> ii32 = np.iinfo(np

In [53]:
np.iinfo(np.int8).min


-128

In [54]:
np.iinfo(np.int32).min


-2147483648

In [55]:
np.iinfo(np.int64).min


-9223372036854775808

In [57]:
np.iinfo(np.int8).max


127

In [59]:
np.iinfo(np.int32).max

2147483647

In [60]:
np.iinfo(np.int64).max

9223372036854775807

In [62]:
help(np.finfo)

Help on class finfo in module numpy:

class finfo(builtins.object)
 |  finfo(dtype)
 |  
 |  finfo(dtype)
 |  
 |  Machine limits for floating point types.
 |  
 |  Attributes
 |  ----------
 |  bits : int
 |      The number of bits occupied by the type.
 |  dtype : dtype
 |      Returns the dtype for which `finfo` returns information. For complex
 |      input, the returned dtype is the associated ``float*`` dtype for its
 |      real and complex components.
 |  eps : float
 |      The difference between 1.0 and the next smallest representable float
 |      larger than 1.0. For example, for 64-bit binary floats in the IEEE-754
 |      standard, ``eps = 2**-52``, approximately 2.22e-16.
 |  epsneg : float
 |      The difference between 1.0 and the next smallest representable float
 |      less than 1.0. For example, for 64-bit binary floats in the IEEE-754
 |      standard, ``epsneg = 2**-53``, approximately 1.11e-16.
 |  iexp : int
 |      The number of bits in the exponent portion of

In [64]:
np.finfo(np.float32).max

3.4028235e+38

In [65]:
np.finfo(np.float64).max

1.7976931348623157e+308

In [66]:
np.finfo(np.float64).min

-1.7976931348623157e+308

In [67]:
np.finfo(np.float32).min

-3.4028235e+38

In [68]:
float_array = np.array([1.5, 2.7, 3.9, 4.2], dtype=np.float32)

In [69]:
float_array.astype(np.int32, copy=False)

array([1, 2, 3, 4])

In [70]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [72]:
matrix - np.mean(matrix, axis=1, keepdims=True)

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [73]:
array = np.array([[4, 2, 5],
                  [1, 6, 3],
                  [7, 0, 8]])

In [74]:
array[np.argsort(array[:, 1])]

array([[7, 0, 8],
       [4, 2, 5],
       [1, 6, 3]])

In [75]:
array[[1, 2]] = array[[2, 1]]

In [76]:
array

array([[4, 2, 5],
       [7, 0, 8],
       [1, 6, 3]])

In [79]:
C = np.array([2, 0, 1, 3, 0, 1])

In [83]:
A = np.repeat(np.arange(len(C)), C)

In [84]:
A

array([0, 0, 2, 3, 3, 3, 5])

In [85]:
np.bincount(A)

array([2, 0, 1, 3, 0, 1], dtype=int64)